version: '3.9'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    env_file: .env
    restart: always
    ports:
      - 8080:8080
    networks:
      - local

networks:
  local:
    external: false
