version: '3.9'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - local

  web:
    build:
      context: ./
      dockerfile: docker/Dockerfile
      target: production
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    restart: always
    networks:
      - local

volumes:
  mysql_data:

networks:
  local:
    external: false
